### ISSUE TITLE
check readme knitting of vignette

### ISSUE THREAD

**Issue by andysouth** [Hackout2/repijson#14]
currently knit('README.Rmd') seems to produce 2 copies of figure. One pointed to from the top of the readme and the other from the correct place.
I only commited the correct one, that leaves a broken link at the top of the readme.

**Comment by thibautjombart** [comment]
I'll check this out today.

**Comment by thibautjombart** [comment]
So, the chunk in question does not produce figures, so it should not try to include one. it works fine on my system.. old version of knitr?

**Comment by andysouth** [comment]
hmmm have updated knitr and it's still creating a figure and inserting this at the top of the readme.

![plot of chunk compileVignette](figure/compileVignette-1.png) 

Perhaps we have different options set for knitr. I don't think I set any. Or a windows/linux thing.
I have to pop out now but will check later.

> packageDescription('knitr')$Version
> [1] "1.10.5"

**Comment by thibautjombart** [comment]
I am using:

> packageDescription('knitr')$Version
> [1] "1.9"
> 
> Can you try disabling the figure in the chunk options? E.g. using
> fig.keep="none"?

**Comment by andysouth** [comment]
Thanks yes fig.keep="none" fixed it.

**Comment by thibautjombart** [comment]
Cool!
