### ISSUE TITLE
pass travis check

### ISSUE THREAD

**Issue by andysouth** [Hackout2/repijson#15]
I've done a few things to get further in the travis check.

Now it fails with :
creating vignettes ... ERROR
Quitting from lines 111-116 (repijson.Rmd)

**Comment by twomagpi** [comment]
passes local check with one note with commit 33bf45d948d21e5108cfbf06479f810c8379b473

**Comment by twomagpi** [comment]
33bf45d948d21e5108cfbf06479f810c8379b473 passes the Travis check

**Comment by thibautjombart** [comment]
Awesome!!
